data:
  label_path: "data/Training400/Fovea_location.xlsx"
  images_path: "data/Training400/"

preprocess:
  resize: [224, 224]

model:
  name: lenet
  channels: 32
  kernel_size: 5
  stride: 1
  input_size: 224
  output_size: 2
  dropout: 0.0
  pretrained: false

optimizer:
  name: Adam
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  name: step
  step_size: 10
  gamma: 0.1

train:
  batch_size: 32
  num_epochs: 50
